@startuml

title __Client Package Diagram__\n


    namespace Client {
      class Client.Bed {
          - bedId : int
          - forSex : String
          - hasSideRoom : boolean
          - status : String
          - wardId : int
          + Bed()
          + getBedId()
          + getForSex()
          + getHasSideRoom()
          + getStatus()
          + getWardId()
          + setSR()
          + setSex()
          + setStatus()
      }
    }

  

    namespace Client {
      class Client.Client {
          + Client()
          + makeDeleteRequest()
          + makeGetRequest()
          + makePostRequest()
          + makePutRequest()
      }
    }

  

    namespace Client {
      class Client.Patient {
          - acceptedByMedicine : boolean
          - arrivalDateTime : LocalDateTime
          - currentBedId : int
          - currentWardId : int
          - dateOfBirth : LocalDate
          - deceased : boolean
          - estimatedDateTimeOfNext : LocalDateTime
          - id : int
          - initialDiagnosis : String
          - needsSideRoom : boolean
          - nextDestination : int
          - patientId : String
          - sex : String
          - suitableForDischargeLounge : boolean
          - transferRequestStatus : String
          - ttaSignedOff : boolean
          + Patient()
          + Patient()
          + Patient()
          + dateFormatter()
          + getAcceptedByMedicine()
          + getArrivalDateTime()
          + getCurrentBedId()
          + getCurrentWardId()
          + getDateOfBirth()
          + getDeceased()
          + getEstimatedTimeOfNext()
          + getId()
          + getInitialDiagnosis()
          + getNeedsSideRoom()
          + getNextDestination()
          + getPatientId()
          + getSex()
          + getSuitableForDischargeLounge()
          + getTransferRequestStatus()
          + getTtaSignedOff()
          + setSex()
      }
    }

  

    namespace Client {
      class Client.Ward {
          - wardId : int
          - wardName : String
          - wardType : String
          + Ward()
          + getWardId()
          + getWardName()
          + getWardType()
      }
    }

  

    namespace Client {
      class Client.fromJson {
          + bedCrossReference()
          + bedsFromJson()
          + crossReference()
          + patientsFromJson()
          + wardsFromJson()
      }
    }

  

  Client.Bed .up.|> java.io.Serializable
  Client.Client -up-|> Client.fromJson
  Client.Patient .up.|> java.io.Serializable
  Client.Ward .up.|> java.io.Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
